#!/usr/bin/env python3
"""Blocks hand-edits to files this project regenerates from source.
PreToolUse hook for Edit|Write|NotebookEdit.
"""
import json
import sys

data = json.load(sys.stdin)
tool_input = data.get("tool_input", {})
file_path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""

if not file_path:
    sys.exit(0)

reason = None
if file_path.endswith(".g.dart"):
    reason = (
        f"{file_path} is generated by build_runner (json_serializable) from its "
        "sibling model file. Hand-edits are silently overwritten on the next build. "
        "Edit the source model file instead, then run: "
        "dart run build_runner build --delete-conflicting-outputs (or 'make build')."
    )
elif file_path.endswith("assets/decks/manifest.json"):
    reason = (
        f"{file_path} is generated by tool/generate_deck_manifest.dart from the deck "
        "JSON files on disk. Hand-edits are overwritten on the next generation. "
        "Edit the deck JSON files instead, then run: make generate-manifest."
    )

if reason:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
